// Package v1 GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package v1

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "http://work-craft.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "GetProfile",
                "tags": [
                    "profile"
                ],
                "summary": "GetProfile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/character": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "CreateCharacter",
                "tags": [
                    "character"
                ],
                "summary": "CreateCharacter",
                "parameters": [
                    {
                        "description": "character",
                        "name": "chat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ProfileController.CharacterType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.Character"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "GetItmes",
                "tags": [
                    "items"
                ],
                "summary": "GetItems",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/items/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "GetUserItmes",
                "tags": [
                    "items"
                ],
                "summary": "GetUserItems",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ProfileController.CharacterType": {
            "type": "object",
            "required": [
                "bottom",
                "eyes",
                "hair",
                "mouth",
                "nose",
                "shoes",
                "top"
            ],
            "properties": {
                "bottom": {
                    "type": "integer",
                    "example": 0
                },
                "eyes": {
                    "type": "integer",
                    "example": 0
                },
                "hair": {
                    "type": "integer",
                    "example": 0
                },
                "mouth": {
                    "type": "integer",
                    "example": 0
                },
                "nose": {
                    "type": "integer",
                    "example": 0
                },
                "other": {
                    "type": "integer"
                },
                "shoes": {
                    "type": "integer",
                    "example": 0
                },
                "top": {
                    "type": "integer",
                    "example": 0
                },
                "weapon": {
                    "type": "integer"
                }
            }
        },
        "profile.Achivement": {
            "type": "object",
            "properties": {
                "icon": {
                    "$ref": "#/definitions/profile.Icon"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "profile.Character": {
            "type": "object",
            "properties": {
                "bottomID": {
                    "type": "integer"
                },
                "eyeID": {
                    "type": "integer"
                },
                "hairID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "mouthID": {
                    "type": "integer"
                },
                "noseID": {
                    "type": "integer"
                },
                "otherID": {
                    "type": "integer"
                },
                "shoeID": {
                    "type": "integer"
                },
                "topID": {
                    "type": "integer"
                },
                "userID": {
                    "type": "string"
                },
                "weaponID": {
                    "type": "integer"
                }
            }
        },
        "profile.Icon": {
            "type": "object",
            "properties": {
                "achivementID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "user": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.User"
                    }
                }
            }
        },
        "profile.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "profile.Statistic": {
            "type": "object",
            "properties": {
                "achivements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.Achivement"
                    }
                },
                "doneQuest": {
                    "type": "integer"
                },
                "earned": {
                    "type": "integer"
                },
                "grade": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "sentQuest": {
                    "type": "integer"
                },
                "spent": {
                    "type": "integer"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "profile.User": {
            "type": "object",
            "properties": {
                "character": {
                    "$ref": "#/definitions/profile.Character"
                },
                "createAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "icon": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.Role"
                    }
                },
                "statistic": {
                    "$ref": "#/definitions/profile.Statistic"
                },
                "verification": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "192.168.1.185",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Profile Work_Craft",
	Description: "This is a profile service.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
